Catalan translation
fairyglade/ly pull request #297
Opened 2021-07-27 16:57 UTC by gerardet46

Hey!
Here's my catalan translation for ly

2022-04-25 23:13 UTC, AnErrupTion requested changes

2022-04-25 23:13 UTC, AnErrupTion commented on res/lang/cat.ini
> +login = iniciar sessió:
Don't put a semicolon.

2022-04-25 23:13 UTC, AnErrupTion commented on res/lang/cat.ini
> +password = Clau:
Same here.

2022-05-04 13:20 UTC, gerardet46 commented on res/lang/cat.ini
> +login = iniciar sessió:
Ok. Done!

2022-05-13 04:41 UTC, AnErrupTion approved these changes

2022-05-13 04:42 UTC, merged