German lang translation
fairyglade/ly pull request #355
Opened 2022-05-13 18:58 UTC by ClientCrash

2022-08-12 16:29 UTC, AnErrupTion requested changes

2022-08-12 16:29 UTC, AnErrupTion commented on res/lang/de.ini
> +err_dgn_oob = log message
Please also translate this.

2022-08-12 16:29 UTC, AnErrupTion commented on res/lang/de.ini
> +login = Anmelden:
Please remove the semicolon.

2022-08-12 16:29 UTC, AnErrupTion commented on res/lang/de.ini
> +password = Passwort:
Same here.

2022-08-19 06:59 UTC, ClientCrash commented
Thanks. I will implement the changes shortly.

2022-08-22 15:58 UTC, merged