Add Ukrainian Translation
fairyglade/ly pull request #362
Opened 2022-05-14 13:26 UTC by KR1470R

Add Ukrainian translation.

2022-06-03 08:09 UTC, AnErrupTion requested changes

2022-06-03 08:09 UTC, AnErrupTion commented on res/lang/ua.ini
> +capslock = capslock
Please translate this as well.

2022-06-03 08:09 UTC, AnErrupTion commented on res/lang/ua.ini
> +login = логін:
Please remove this semicolon.

2022-06-03 08:09 UTC, AnErrupTion commented on res/lang/ua.ini
> +password = пароль:
Please remove this semicolon.

2022-06-03 08:09 UTC, AnErrupTion commented on res/lang/ua.ini
> +numlock = numlock
Please translate this as well.

2022-06-03 08:09 UTC, AnErrupTion commented on res/lang/ua.ini
> +shell = shell
Please translate this as well.

2022-06-03 09:32 UTC, KR1470R commented on res/lang/ua.ini
> +capslock = capslock
it doesn't translate to ukrainian as well

2022-06-03 09:32 UTC, KR1470R commented on res/lang/ua.ini
> +numlock = numlock
it doesn't translate to ukrainian as well

2022-06-10 14:23 UTC, KR1470R commented
@AnErrupTion hey! i've pushed fixes, can u merge it pls?

2022-08-12 13:10 UTC, AnErrupTion commented
Sorry I took this long! Will merge.

2022-08-12 13:11 UTC, merged