Make it easy to install ly on runit systems e.g. void
fairyglade/ly pull request #431
Opened 2022-08-21 15:19 UTC by erkannt

Copied nearly wholesale from https://github.com/drozdowsky/ly-void.

I only updated the Makefile and README to match what I could see for openrc.

2022-08-22 00:37 UTC, Cavernosa commented on readme.md
> +# make
Why is there sh highlighting here? 
also `make` alone doesn't need root permissions

2022-08-22 07:38 UTC, erkannt commented on readme.md
> +# make
I was trying to follow what came above. `sh` highlighting just out of habit. Happy to remove it.

Would you prefer: 

```
make
make install installrunit
ln -s /etc/sv/ly /var/service/
```

or:

```
$ make
# make install installrunit
# ln -s /etc/sv/ly /var/service/
```

or:

```
make
sudo make install installrunit
sudo ln -s /etc/sv/ly /var/service/
```

I've got no preferences.

2022-08-22 15:59 UTC, AnErrupTion commented on readme.md
> +# make
Highlighting makes sense here, as other stuff above also has it.

2022-08-22 16:00 UTC, AnErrupTion requested changes

2022-08-22 16:00 UTC, AnErrupTion commented on readme.md
> +# make
``make`` itself doesn't require root, so please update it to the correct symbol ($)

2022-08-23 00:08 UTC, Cavernosa commented on readme.md
> +# make
> Would you prefer:

2nd one is what i meant. Just like AnErrupTion said in the change request below.

>Highlighting makes sense here, as other stuff above also has it.

What do you mean? No other code block has `sh` highlighting and `sh` highlight is not meant for CLI (as evident here, it's thinking the commands are comments).

2022-08-26 07:09 UTC, erkannt commented on readme.md
> +# make
Done.

2022-08-28 10:53 UTC, merged