Making Ly animations easily extendable
fairyglade/ly pull request #507
Opened 2023-05-26 02:14 UTC by SladeGetz

I consolidated the animation functions into their own .c and .h file (removed from draw) and made it much easier to add new animations by simply modifying `#define ANIMATION_NUM ...` on line 32 of `src/animations.c` and adding your animation init, run, and free functions to the arrays `static const void* ANIM_INITS[]`, `static const void* ANIM_RUNS[]`, and `static const void* ANIM_FREES[]` on lines 43, 47, and 51, respectively.

2023-06-15 07:09 UTC, AnErrupTion requested changes
Hey! I personally like your chances, although I had 2 things to say. Could you rebase your PR on master too please? Thanks!

2023-06-15 07:09 UTC, AnErrupTion commented on src/animations.c
> +
I'm perosnally not a huge fan of this. In my opinion, it decreases code readability too much for what is a minor improvement.

2023-06-15 07:09 UTC, AnErrupTion commented on src/draw.h
>  void draw_free(struct term_buf* buf);
``draw_free()`` doesn't seem to be used anymore, perhaps it could be removed?

2023-08-30 05:07 UTC, Flixnore commented
Any plans to continue this? Just found Ly and hoping to make my own animations.

2023-09-04 18:16 UTC, SladeGetz commented
Moved to #541

2023-09-04 18:16 UTC, closed without merging