Zig Rewrite - Zig 0.12.0 and more!
fairyglade/ly pull request #599
Opened 2024-04-21 10:12 UTC by Kawaii-Ash

# Changes

+ updated to use Zig v0.12.0
+ allocator is no longer needed in `authenticate`
+ replaced some functions in interop to use the Zig equivalent
+ mapped `blank_password` to `clear_password` for compatibility with old config
+ cursor is set to the end of the user input when next focused after loading from a save file
+ `save.ini` is expected to be in the same dir as the config
+ changed save migrator to load from old save format correctly. (loads file from `config.save_file`)
+ some general code improvements

2024-04-21 17:53 UTC, AnErrupTion requested changes

2024-04-21 17:53 UTC, AnErrupTion commented on src/main.zig
> +                        try info_line.setText(lang.err_console_dev);
Why was this removed?

2024-04-21 17:53 UTC, AnErrupTion commented on src/config/migrator.zig
> +    std.fs.deleteFileAbsolute(old_path) catch {};
Should we do this? This would execute even if `config.save` is false. And, even if it was always true, we'll save it later on anyway.

2024-04-21 17:53 UTC, AnErrupTion commented on src/auth.zig
> +        interop.endusershell();
Use `defer` here for consistency with other code.

2024-04-21 17:53 UTC, AnErrupTion commented on src/auth.zig
> +fn setXdgEnv(tty_str: [:0]u8, desktop_name: [:0]const u8, desktop_names: [:0]const u8) !void {
Name it `xdg_desktop_name` instead of `desktop_names` for better clarity.

2024-04-21 17:53 UTC, AnErrupTion commented on src/auth.zig
> +    _ = interop.setenv("XDG_CURRENT_DESKTOP", desktop_names.ptr, 0);
We should only set those environment variables if we have an XDG name (so if we aren't launching a TTY/shell for example).

2024-04-21 17:53 UTC, AnErrupTion commented on src/auth.zig
> +    _ = interop.setenv("XDG_SESSION_DESKTOP", desktop_name.ptr, 0);
Should be `desktop_names`, not `desktop_name`.

2024-04-21 17:53 UTC, AnErrupTion commented on src/auth.zig
> +        std.process.exit(1);
Why is the exit status code `1` here instead of `0` like before?

2024-04-21 17:53 UTC, AnErrupTion commented on src/auth.zig
> +        std.process.exit(1);
Same here.

2024-04-21 17:53 UTC, AnErrupTion commented on src/auth.zig
> +        std.process.exit(1);
Same here.

2024-04-21 17:53 UTC, AnErrupTion commented on src/auth.zig
> +
Remove space here. :)

2024-04-21 17:53 UTC, AnErrupTion commented on src/auth.zig
> +    _ = std.c.waitpid(x_pid, &status, 0);
Any reason `std.c.waitpid()` is used here instead of `std.posix.waitpid()`?

2024-04-21 19:00 UTC, Kawaii-Ash commented on src/main.zig
> +                        try info_line.setText(lang.err_console_dev);
The function used to use an allocator. The only error it can return now is `error.CannotOpenConsoleDev`.

2024-04-21 19:08 UTC, Kawaii-Ash commented on src/auth.zig
> +    _ = std.c.waitpid(x_pid, &status, 0);
The process might not exist or it might need some time to be killed. 
If the process doesn't exist, `std.posix.waitpid` will go to `unreachable`.

2024-04-21 19:12 UTC, Kawaii-Ash commented on src/auth.zig
> +        std.process.exit(1);
Since it replaces the process, the only scenario it should reach that point is if an error occurred.

2024-04-21 19:23 UTC, Kawaii-Ash commented on src/auth.zig
> +    _ = interop.setenv("XDG_SESSION_DESKTOP", desktop_name.ptr, 0);
Taking a quote from the arch wiki: "`XDG_SESSION_DESKTOP` is similar to `XDG_CURRENT_DESKTOP,` but only permits a single string."

`desktop_names` could be a colon separated list, meaning it wouldn't be suitable to set `XDG_SESSION_DESKTOP`.

2024-04-21 20:46 UTC, Kawaii-Ash commented on src/auth.zig
> +        interop.endusershell();
Consistency with what other code?

2024-04-21 21:51 UTC, Kawaii-Ash commented on src/config/migrator.zig
> +    std.fs.deleteFileAbsolute(old_path) catch {};
that's a good point

2024-04-21 22:53 UTC, AnErrupTion commented on src/auth.zig
> +    _ = interop.setenv("XDG_SESSION_DESKTOP", desktop_name.ptr, 0);
Then we should split `xdg_desktop_names` and take like the first item. But we shouldn't set it to `desktop_name`, because that's often separated with spaces (thus not really a single string).

2024-04-21 22:56 UTC, AnErrupTion commented on src/auth.zig
> +        interop.endusershell();
What I mean is it'd be consistent, as in using `defer` to deinitialize (or in this case, "end") a structure or anything else, just like across the code base.

2024-04-22 06:37 UTC, Kawaii-Ash commented on src/auth.zig
> +        interop.endusershell();
it'd be the only usage of defer where a following operation can't fail.

2024-04-22 07:11 UTC, AnErrupTion commented on src/auth.zig
> +        interop.endusershell();
That'd be `errdefer` though, not `defer`. The latter can be used in every situation, as in, the statement will always be executed.

2024-04-22 08:38 UTC, Kawaii-Ash commented on src/auth.zig
> +        interop.endusershell();
```
{
    startusershell();
    getusershell();
    endusershell();
}
```
In this situation, `getusershell()` will not result in an error. so `endusershell()` will always execute afterwards. 

It'd only be consistent with the rest of the codebase if the code was as follows:
```
{
    startusershell();
    defer endusershell();
    try getusershell();
}
```
It is otherwise a meaningless change. 
If changes such as this are requested, an explicit style guide should be written down to make it clear.

2024-04-22 08:54 UTC, Kawaii-Ash commented on src/auth.zig
> +    _ = interop.setenv("XDG_SESSION_DESKTOP", desktop_name.ptr, 0);
`DesktopNames` is not required in the session file and could lead to `XDG_SESSION_DESKTOP` not being set in this case.

I don't see any issues regarding `XDG_SESSION_DESKTOP` being set incorrectly in the C version. 
Keeping the current behaviour seems to be more correct.

2024-04-22 09:07 UTC, Kawaii-Ash commented on src/auth.zig
> +    _ = interop.setenv("XDG_SESSION_DESKTOP", desktop_name.ptr, 0);
The value for `XDG_SESSION_DESKTOP` could possibly be taken from the name of the session file, but there has been no reported issues about changing it thus far.

2024-04-22 11:24 UTC, AnErrupTion commented on src/auth.zig
> +    _ = interop.setenv("XDG_SESSION_DESKTOP", desktop_name.ptr, 0);
> `DesktopNames` is not required in the session file and could lead to `XDG_SESSION_DESKTOP` not being set in this case.

Then we could fallback to `desktop_name` if that's the case.

> I don't see any issues regarding `XDG_SESSION_DESKTOP` being set incorrectly in the C version. 
> Keeping the current behaviour seems to be more correct.

Most likely because not many applications check for it, but that doesn't mean it's set correctly.

2024-05-01 16:46 UTC, AnErrupTion approved these changes
Thank you for your contribution!

2024-05-01 16:46 UTC, merged