Various bug fixes and small features
fairyglade/ly pull request #606
Opened 2024-05-13 20:26 UTC by Kawaii-Ash

This PR includes some small features and bug fixes.

Features:
+ Custom info text
+ Shift+Tab for navigation
+ Setting numlock at startup
+ Set info line when authenticating
+ Changed build.zig to reintroduce `DESTDIR` and `NAME`

Bug Fixes:
+ Stray Cursor
+ Integer overflows
+ Cascade

Related Issues: 
+ #602 (Stray Cursor)
+ #334 
+ #470 
+ #490
+ #605

2024-06-15 20:57 UTC, AnErrupTion requested changes

2024-06-15 20:57 UTC, AnErrupTion commented on build.zig
> +        .optimize = if (optimize == .ReleaseSafe) .ReleaseFast else optimize,
We definitely shouldn't do that. Since this is most likely a Zig compiler bug, let it crash with a runtime error for now if ReleaseSafe is used. (Perhaps it has been fixed in Zig 0.13.0?)

2024-06-15 20:57 UTC, AnErrupTion commented on build.zig
> +        std.fs.cwd().makePath(exe_path) catch {};
Add a warning message for consistency.

2024-06-15 20:57 UTC, AnErrupTion commented on build.zig
> +        std.fs.cwd().makePath(pam_path) catch {};
Same here.

2024-06-15 20:57 UTC, AnErrupTion commented on build.zig
> +                std.process.exit(1);
Purposefully crashing the build process is a pretty nuclear option in my opinion. We should just let it return `version_str`.

2024-06-15 20:57 UTC, AnErrupTion commented on build.zig
> +                std.process.exit(1);
Same here.

2024-06-15 20:57 UTC, AnErrupTion commented on src/interop.zig
> +pub const termbox = @import("termbox2");
Because termbox is imported as a Zig module now, it shouldn't be in `interop.zig`.

2024-06-15 20:57 UTC, AnErrupTion commented on src/auth.zig
> +
Is all of this really needed? Can't we just use `std.process` to start the process and forward its output to a buffer?

2024-06-15 20:57 UTC, AnErrupTion commented on src/main.zig
> +                    var file = std.fs.cwd().createFile(save_path, .{}) catch break :save_last_settings;
I feel like allowing a relative path here is trying to shoot ourselves in the foot. Where exactly would the CWD be? In `/usr/bin`? Perhaps `/etc/ly`? This is too ambiguous, in my opinion.

2024-06-15 20:57 UTC, AnErrupTion commented on src/bigclock.zig
> +const ZERO = [_]u21{
I'm not convinced by the space savings of this, given the potential runtime cost. Why was this change made?

2024-06-15 20:57 UTC, AnErrupTion commented on src/auth.zig
> +    if (pam_env_vars == null) return error.GetEnvListFailed;
You've introduced some errors that aren't handled in `main.getAuthErrorMsg()`. This is one of them.

2024-06-15 20:57 UTC, AnErrupTion commented on src/auth.zig
> +    return buf;
Same here.

2024-06-15 20:57 UTC, AnErrupTion commented on src/auth.zig
> +    if (status.status != 0) return error.XauthFailed;
Same here.

2024-06-15 20:57 UTC, AnErrupTion commented on src/auth.zig
> +            if (e == error.ProcessNotFound and ok != 0) return error.XcbConnectionFailed;
Same here.

2024-06-19 12:41 UTC, Kawaii-Ash commented on src/bigclock.zig
> +const ZERO = [_]u21{
Since a codepoint is 21 bits, it's the correct type to be using. 
The runtime cost is minimal and I don't think it's worth using the wrong type. 

Are we aiming for slightly better performance at the expense of correctness or the opposite?

2024-06-19 12:57 UTC, Kawaii-Ash commented on build.zig
> +        .optimize = if (optimize == .ReleaseSafe) .ReleaseFast else optimize,
I'm not sure completely breaking builds in ReleaseSafe is desired when only a single step needs to be overridden, especially when it is considered the "main release mode". 

Editing the comment above it to read: `// HACK: Only fails with ReleaseSafe, so we'll override it for now`, would be a better indicator to change it in the future.

2024-06-19 13:09 UTC, Kawaii-Ash commented on build.zig
> +                std.process.exit(1);
Stopping the build process in such situations is beneficial, since it's an indicator that `ly_version` is set incorrectly.

2024-06-19 13:27 UTC, Kawaii-Ash commented on src/auth.zig
> +
It's in a fork child, so you want to avoid heap allocation and use functions in `std.posix`. Alternatively, mcookie could be removed as a dependency and it could be implemented directly in Zig in ~5 lines.

2024-06-19 13:51 UTC, Kawaii-Ash commented on src/main.zig
> +                    var file = std.fs.cwd().createFile(save_path, .{}) catch break :save_last_settings;
The cwd is the directory the current user is in or with systemd for example, u set it with `WorkingDirectory=`.
The other paths, for the lang/config can also be a relative path, so it's consistent. 

At times, I'd create a directory with a config just for testing, then I'd provide a relative path to it, which is a lot faster than providing an absolute path. 

I don't see it being used outside of testing things and I'm not sure it should be taken away since a user would hopefully be aware when they're using a relative path.

2024-06-19 13:56 UTC, Kawaii-Ash commented on src/interop.zig
> +pub const termbox = @import("termbox2");
The only reason it's imported in such a way is due to the workaround to fix ReleaseSafe builds. Probably not worth changing imports across the codebase due to a workaround.

2024-06-19 18:12 UTC, AnErrupTion commented on build.zig
> +        .optimize = if (optimize == .ReleaseSafe) .ReleaseFast else optimize,
I'm more concerned about the safety issues it may create. In ReleaseSafe, safety checks (like overflowing, array index out of bounds, etc...) are kept, but not in ReleaseFast. This could potentially dismiss some bugs in Ly by making it automatically build in ReleaseFast even when ReleaseSafe is selected.

2024-06-19 18:18 UTC, AnErrupTion commented on src/interop.zig
> +pub const termbox = @import("termbox2");
I don't really understand this... how is the current workaround related to the file in which the module is imported?

2024-06-19 18:19 UTC, AnErrupTion commented on src/auth.zig
> +
> Alternatively, mcookie could be removed as a dependency and it could be implemented directly in Zig in ~5 lines.

Honestly that doesn't sound like a bad idea. Other than that, I understand the reasons why `std.process` isn't used.

2024-06-19 18:21 UTC, AnErrupTion commented on src/bigclock.zig
> +const ZERO = [_]u21{
> Are we aiming for slightly better performance at the expense of correctness or the opposite?

Oh right, I just didn't understand why the change was made. If it's for correctness, it's fine (Ly doesn't need to be that fast anyway, though of course we shouldn't make it slower for silly reasons).

2024-06-19 18:25 UTC, AnErrupTion commented on src/main.zig
> +                    var file = std.fs.cwd().createFile(save_path, .{}) catch break :save_last_settings;
> The cwd is the directory the current user is in or with systemd for example, u set it with WorkingDirectory=.

Ah right, I suppose that makes sense (and for other init systems using shell scripts, `cd` should work).

2024-06-27 02:50 UTC, Kawaii-Ash commented on build.zig
> +        .optimize = if (optimize == .ReleaseSafe) .ReleaseFast else optimize,
As I understand it:
The rest of the project should still have safety checks outside of that module.
Without it, you're forced to compile the whole project with ReleaseFast/ReleaseSmall, so there would be no safety checks at all. 

This temporary workaround is the best case scenario imo.

2024-06-27 02:59 UTC, Kawaii-Ash commented on src/interop.zig
> +pub const termbox = @import("termbox2");
Normally, it'd be imported like below, but the build mode can't be overridden in this case. 

```
const termbox = @cImport({
    @cDefine("TB_IMPL", {});
    @cInclude("termbox2.h");
});
```

2024-06-27 03:34 UTC, Kawaii-Ash commented on src/auth.zig
> +
If it's something u want to consider at some point, I threw this together:

```zig
pub fn mcookie() [32]u8 {
    var buf: [4096]u8 = undefined;
    std.crypto.random.bytes(&buf);

    var out: [16]u8 = undefined;
    Md5.hash(&buf, &out, .{});

    return std.fmt.bytesToHex(&out, .lower);
}
```

2024-06-29 08:04 UTC, AnErrupTion commented on build.zig
> +        .optimize = if (optimize == .ReleaseSafe) .ReleaseFast else optimize,
Fair enough. However, we should not just have a comment indicating the hack, but also print a message to potentially warn the user (this may not matter for automated buildbots like for distributions, but it's still better than othing).

2024-07-02 00:01 UTC, Kawaii-Ash commented on build.zig
> +        .optimize = if (optimize == .ReleaseSafe) .ReleaseFast else optimize,
I added a warning.

2024-07-02 08:51 UTC, AnErrupTion approved these changes

2024-07-02 08:52 UTC, merged