Added keybinds to control brightness
fairyglade/ly pull request #626
Opened 2024-07-01 22:39 UTC by tubi16

Added keybinds to control brightness with brightnessctl. 

F5 to decrease brightness.
f6 to increase brightness.

2024-07-02 09:26 UTC, AnErrupTion requested changes

2024-07-02 09:26 UTC, AnErrupTion commented on src/main.zig
> +});
Please include this in `interop.zig` instead, and rename it `unistd`, like so:

```suggestion
const unistd = @cImport({
    @cInclude("unistd.h");
});
```

2024-07-02 09:26 UTC, AnErrupTion commented on src/main.zig
> +                    }
Please implement the following configuration options, along with their respective default values, in `res/config.ini` and `src/config/Config.zig`:

- `brightness_down_key`, whose default should be `f5` (you can parse it the same way as `shutdown_key` and the others)
- `brightness_up_key`, whose default should be `f6` (same as `brightness_down_key`)
- `brightnessctl`, whose default should be `/usr/bin/brightnessctl`

Please also make the brightness key hints show up on the screen, just like the shutdown & reboot keys for example.

Optionally, you can also implement a `brightness_change` option whose default would be `5%` (as I believe `5%` to be a pretty arbitrary choice), but you don't need to.

2024-07-03 14:36 UTC, tubi16 commented on src/main.zig
> +                    }
I am gonna do it.  Should I fork latest changes and then make pull request?

2024-07-03 15:33 UTC, AnErrupTion commented on src/main.zig
> +                    }
No need to, you can do it in this PR directly.

2024-07-03 17:48 UTC, tubi16 commented
@AnErrupTion can you check?  Is ıt as you wanted?

+ brightnessctl package may wanted as dep.

2024-07-03 18:00 UTC, AnErrupTion requested changes
Just a few changes needed to be done, otherwise it looks good!

2024-07-03 18:00 UTC, AnErrupTion commented on src/main.zig
>                  }
Instead of assuming the allocation will always succeed, it may be better instead to set the info line to the `err_alloc` error and break out of the inner condition, like so (same applies for the brightness down key, too):

```suggestion
                } else if (pressed_key == brightness_up_key and unistd.access(&config.brightnessctl[0], unistd.X_OK) == 0) brightness_change: {
                    const brightness_str = std.fmt.allocPrint(allocator, "+{s}%", .{config.brightness_change}) catch {
                        try info_line.setText(lang.err_alloc);
                        break :brightness_change;
                    };
                    defer allocator.free(brightness_str);
                    var brightness = std.ChildProcess.init(&[_][]const u8{ config.brightnessctl, "-q", "s", brightness_str }, allocator);
                    _ = brightness.spawnAndWait() catch .{};
                }
```

2024-07-03 18:01 UTC, AnErrupTion commented
> @AnErrupTion can you check? Is ıt as you wanted?
> 
>     * brightnessctl package may wanted as dep.

It can be added as a runtime dependency in the `README.md` file, sure.

2024-07-03 19:10 UTC, tubi16 commented on src/main.zig
>                  }
Done.

2024-07-03 21:14 UTC, AnErrupTion requested changes

2024-07-03 21:14 UTC, AnErrupTion commented on src/config/Lang.zig
> +err_brightness_change: []const u8 = "failed to change brightness",
Please add this in the `res/lang/en.ini` file as well.

2024-07-03 22:04 UTC, tubi16 commented on src/config/Lang.zig
> +err_brightness_change: []const u8 = "failed to change brightness",
Added ^^

2024-07-04 11:17 UTC, AnErrupTion approved these changes
Thanks for your changes!

2024-07-04 11:17 UTC, merged