feat: support zig `0.13.0`
fairyglade/ly pull request #632
Opened 2024-07-03 11:55 UTC by jinzhongjia

Add zig `0.13.0` adaptation

2024-07-03 11:58 UTC, jinzhongjia commented
What do you think of trying to add github action to support CI?
@AnErrupTion

2024-07-03 12:00 UTC, AnErrupTion approved these changes

2024-07-03 12:02 UTC, jinzhongjia commented
Good CI can help ensure certain build compatibility
But if you only maintain compatibility with the latest release zig, there is no need.

2024-07-03 12:03 UTC, jinzhongjia commented
After all, sometimes the person who initiated the PR may not do a complete version compatibility test.

2024-07-03 12:10 UTC, jinzhongjia commented
The current problem is caused by clap in latest version being incompatible with version 12.
Need to open pr to clap

2024-07-03 12:18 UTC, AnErrupTion commented
> The current problem is caused by clap in latest version being incompatible with version 12. Need to open pr to clap

I don't think clap maintains backwards compatibility with older versions of Zig either, you'll have to check with them on that.

2024-07-03 15:40 UTC, jinzhongjia commented
acorrding this issue,https://github.com/Hejsil/zig-clap/issues/128

It seems that not to be backward compatible

2024-07-04 00:35 UTC, jinzhongjia commented
ok , clap has agreed to maintain backward compatibility with current 12

2024-07-04 00:36 UTC, jinzhongjia commented
We just need to wait for clap to merge pr.

2024-07-05 07:46 UTC, jinzhongjia commented
Now clap's pr has been merged, `zigini` still has a little problem, but I have opened a PR

2024-07-05 07:46 UTC, jinzhongjia commented
https://github.com/Kawaii-Ash/zigini/pull/1

2024-07-05 07:48 UTC, jinzhongjia commented
We currently only need to wait for the PR merge to be completed. My local test of `0.12` and `0.13` has passed.

2024-07-05 08:27 UTC, jinzhongjia commented
this issue: https://github.com/fairyglade/ly/issues/225

Added option for build: `default_tty`
@AnErrupTion please review my commit again. I'm not sure if it's correct.

2024-07-05 08:29 UTC, AnErrupTion requested changes

2024-07-05 08:29 UTC, AnErrupTion commented on build.zig
> +var default_tty: u8 = 0;
You can make it `undefined` instead of `0`.

2024-07-05 08:29 UTC, AnErrupTion commented on build.zig
> +
Minor nitpick: for consistency sake, please add proper capitalization (e.g. "Set default TTY").

2024-07-05 10:32 UTC, AnErrupTion approved these changes

2024-07-05 13:43 UTC, jinzhongjia commented
now, everything should be ok

2024-07-12 20:39 UTC, AnErrupTion commented
Thanks for your contribution!

2024-07-12 20:40 UTC, merged