Add customizable foreground color to CMatrix
fairyglade/ly pull request #652
Opened 2024-07-14 21:17 UTC by 0xNiffin

Just wanted to be able to change the color on the CMatrix characters :)

2024-07-17 11:30 UTC, AnErrupTion requested changes

2024-07-17 11:30 UTC, AnErrupTion commented on res/config.ini
> +animation = matrix
Please don't change the default option to use an animation.

2024-07-17 11:30 UTC, AnErrupTion commented on res/config.ini
> +#CMatrix foreground color id
Please add a space after the `#` for consistency. :)

2024-07-17 11:30 UTC, AnErrupTion commented on res/config.ini
> +Brightness_change = 10
I didn't see this beforehand but please use a lowercase `b` here.

2024-07-17 11:30 UTC, AnErrupTion commented on src/animations/Matrix.zig
> +pub fn draw(self: *Matrix, fg_ini: u16) void {
Please add `fg_ini` as a field in `Matrix` instead.

2024-07-17 11:30 UTC, AnErrupTion commented on src/animations/Matrix.zig
> +            var fg: u16 = fg_ini;
You can also get rid of this variable.

2024-07-17 19:47 UTC, 0xNiffin commented
Sorry it's my first time dealing with something in Zig haha

I've made a commit with the new changes, for some weird reason it's not letting me change the `var fg: u16 = @intCast(termbox.TB_GREEN);` as it is not present the code.

Could you please elaborate on how I could add that variable as a field? I've looked at the documentation but left confused.

Thanks in advance! Cheers

2024-07-19 22:46 UTC, 0xNiffin commented
Hello again!

Did the changes your requested, I've also noticed that the capital B (res/config.ini) is actually present in the main branch of ly.

Cheers

2024-07-22 14:44 UTC, AnErrupTion commented
> I've also noticed that the capital B (res/config.ini) is actually present in the main branch of ly.

Yup, I simply didn't notice that when merging the PR that had these changes. Other than that, the changes look good, thanks!

2024-07-22 14:44 UTC, AnErrupTion approved these changes

2024-07-22 14:44 UTC, merged