Adjust Doom Animation Speed using config.ini
fairyglade/ly pull request #658
Opened 2024-07-22 15:22 UTC by 0xNiffin

Implemented a way to adjust Doom animation speed through the config file and also changed Config.zig so it stays in alphabetical order :) hope that's ok! 

Cheers 🍻

2024-07-26 17:09 UTC, AnErrupTion requested changes

2024-07-26 17:09 UTC, AnErrupTion commented on res/config.ini
> +doom_delay = 0
This delay should ideally be generic and also be used in the Matrix animation.

2024-07-29 18:10 UTC, 0xNiffin commented on res/config.ini
> +doom_delay = 0
From the testing I've done this only works well with the Doom animation.

I've implemented it in the Matrix animation as well but it ends up just looking very laggy and clunky by just adding 1ms to it.

Cheers

2024-07-31 20:13 UTC, 0xNiffin commented on res/config.ini
> +doom_delay = 0
Ahhh yes, you're right. I didn't notice that option. My bad. 

Cheers

2024-07-31 20:18 UTC, closed without merging