Add display of error messages
fairyglade/ly pull request #661
Opened 2024-07-27 13:12 UTC by moabeat-berlin

Addressing issue #646, where the config file got silently ignored.

2024-07-27 13:28 UTC, AnErrupTion reviewed
While the changes look fine to me otherwise, I'm not a huge fan of introducing another type (`ErrorMessages`) alongside `InfoLine`. I think it's better if an info line takes a parameter to indicate if it's an error, and if so, render it with the error foreground & background colors.

Also, what I planned to do originally was extend the `InfoLine` to add a list of messages instead of just the current one, so you'd be able to cycle through them in the UI at runtime. But of course, you're not in my head so you couldn't have known. :D

2024-07-27 13:28 UTC, AnErrupTion commented on res/config.ini
> +
Is there any "specification" for 16-bit colors like these? It might be interesting to add a comment referring to it, so users can easily change the colors if they wanted to.

2024-07-27 13:42 UTC, moabeat-berlin commented on res/config.ini
> +
During development, I tried to set the color to `termbox.TB_RED | termbox.TB_BOLD`, like this is similarly done in the matrix animation [here](https://github.com/fairyglade/ly/blob/e775827c8b18d5300c3300486facbfe2e6377436/src/animations/Matrix.zig#L158C44-L158C78). This ended up with the value of `258` not fitting into an `u8`. Also the [colors in termbox2](https://git.sr.ht/~kolunmi/termbox2-zig/tree/master/item/include/termbox2.h#L248) seem to be in `u16`. Therefore I changed it accordingly.

2024-07-27 13:46 UTC, AnErrupTion commented on res/config.ini
> +
No problem then, but then I think it's wise to add a comment explaining what the default value is (i.e. `TB_RED | TB_BOLD`).

2024-07-27 13:47 UTC, moabeat-berlin commented
Well, in the best case, no errors are shown at all. :smile_cat: I would think this way it is more obvious, that something is wrong in or with the config. But in the end, it's your design and decision to adopt it like it is now. For me, it would have been a great help and maybe it can be further improved along the way.

2024-07-27 13:50 UTC, AnErrupTion commented
> Well, in the best case, no errors are shown at all. 😸 I would think this way it is more obvious, that something is wrong in or with the config. But in the end, it's your design and decision to adopt it like it is now. For me, it would have been a great help and maybe it can be further improved along the way.

Of course! What you can do is extend `InfoLine` to use an array, similar to what you did in `ErrorMessages`, but for now continue to show only the last message in the UI. I can work on adding the rest myself.

2024-07-27 14:21 UTC, moabeat-berlin commented
> Of course! What you can do is extend `InfoLine` to use an array, similar to what you did in `ErrorMessages`, but for now continue to show only the last message in the UI. I can work on adding the rest myself.

Alright, sounds good! I will look into this tomorrow.

2024-07-28 09:44 UTC, AnErrupTion requested changes
Overall the changes look good, just a few minor nitpicks here and there!

2024-07-28 09:44 UTC, AnErrupTion commented on src/main.zig
> +    if (!build_options.enable_x11_support) try info_line.addError(lang.no_x11_support);
I wouldn't consider this an error, but just as a simple information to know.

2024-07-28 09:44 UTC, AnErrupTion commented on src/main.zig
> +            try info_line.addError("Unable to parse config file");
Please add this in `src/config/Lang.zig` and in `res/lang/en.ini` as something like `err_config`.

2024-07-28 09:44 UTC, AnErrupTion commented on src/main.zig
> +                    info_line.setText(getAuthErrorMsg(err, lang));
That's considered an error, so please make use of `addError` here.

2024-07-28 09:44 UTC, AnErrupTion commented on src/tui/components/InfoLine.zig
> +    const width: u8 = if (text.len > 0) try utils.strWidth(text) else 0;
You should avoid recalculating the width every time since it's pointless. What you can do is create an `ErrorMessage` struct and store the text and its width inside it, instead of storing just the text in the array list.

2024-07-28 09:55 UTC, moabeat-berlin commented on src/main.zig
> +            try info_line.addError("Unable to parse config file");
The issue here is, that the language file is read only _after_ the config file and it depends on the config, which language file is chosen.

2024-07-28 09:59 UTC, moabeat-berlin commented on src/tui/components/InfoLine.zig
> +    const width: u8 = if (text.len > 0) try utils.strWidth(text) else 0;
When testing my code, I came across a situation when the error text was not centered. This is the case if an error gets added _before_ the info text is set some time later in the code. Since the error has precedence over the info text, it was using the width of the info text while displaying the (longer) error. Didn't look good. To overcome this, put the with calculation in the draw method, so that it is always correct.

2024-07-28 10:22 UTC, AnErrupTion commented on src/tui/components/InfoLine.zig
> +    const width: u8 = if (text.len > 0) try utils.strWidth(text) else 0;
Yes, so what I meant is that you add an `ErrorMessage` struct that looks like this:

```zig
const ErrorMessage = struct { width: u8, text: []const u8 };
```

So in `addError()`, you would calculate the width of the error message and store it in the struct. Same for `setText()`, but you can just add a `text_width: u8` field in the `InfoLine` struct for that. Then, in `draw()`, you just select the appropriate width given the text you're drawing.

2024-07-28 10:23 UTC, AnErrupTion commented on src/main.zig
> +            try info_line.addError("Unable to parse config file");
Oh yeah, I forgot about that. In this case that's fine, however please add a comment explaining that (mandatory) choice. Also, a minor nitpick: `Unable` should be `unable` to match the style of other messages :D

2024-07-28 10:47 UTC, moabeat-berlin commented on src/tui/components/InfoLine.zig
> +    const width: u8 = if (text.len > 0) try utils.strWidth(text) else 0;
Alright, done.

2024-07-28 10:47 UTC, moabeat-berlin commented on src/main.zig
> +            try info_line.addError("Unable to parse config file");
Also done as requested.

2024-07-28 11:02 UTC, AnErrupTion approved these changes
LGTM. Thanks for your contribution!

2024-07-28 11:02 UTC, merged