Adds Farsi Bigclock
fairyglade/ly pull request #673
Opened 2024-08-02 22:38 UTC by KAYT33N

Hi
I'll open up what each commit does

### 1. Change config type for bigclock
This used to be a "on/off" boolean and I had to either add a new value for language or change this to enum
So I changed it from boolean to enum with following values
"none (default)", "en", "fa"

### 2. Separates big clock's hard codes from its logic
"bigclock.zig" file was already too big to have another language added to it so I separated the clock chars from the functions
This also makes adding new regional or custom numbers sets as easy as filling the "bigclock.Lang.LocaleChars" struct

### 3. Adds Farsi (fa) to big clock langs
This commit creates "fa.zig" file and registers it in codes

### Screenshot
![image](https://github.com/user-attachments/assets/691744f8-3dc3-4ae8-bb1f-49475fae9768)

Time was : 01:35 -> ۰۱:۳۵

2024-08-03 05:42 UTC, AnErrupTion requested changes
Overall very nice changes, thank you! Just a couple, small more things needed.

2024-08-03 05:42 UTC, AnErrupTion commented on res/config.ini
> +bigclock = none
Please add this change into the config migrator to ensure backwards compatibility. Essentially, all you need to do is make sure the previous boolean value gets converted into the appropriate enum value (so `false` = `none` and `true` = `en`).

2024-08-03 05:42 UTC, AnErrupTion commented on src/bigclock/en.zig
> +pub const locale_chars = LocaleChars{
Please make sure to keep the ``// zig fmt: off`` and ``// zig fmt: on`` comments here.

2024-08-03 05:42 UTC, AnErrupTion commented on src/bigclock/fa.zig
> +pub const locale_chars = LocaleChars{
Same here.

2024-08-03 05:42 UTC, AnErrupTion commented on src/bigclock.zig
> +    };
In Zig, if you handle all enum possibilities (here `.en` and `.fa`), you don't have to provide an `else` branch. Please do that here.

2024-08-07 06:51 UTC, KAYT33N commented on src/bigclock.zig
> +    };
Actually it gives compile error without the `else` branch because of the `none` variant

2024-08-07 08:47 UTC, AnErrupTion commented on src/bigclock.zig
> +    };
@KAYT33N You can simply use `unreachable` in the `.none` branch, since we know we can't reach that branch.

2024-08-07 08:53 UTC, AnErrupTion commented on src/config/migrator.zig
> +            mapped_field.value = "none";
You can just use an inlined condition here, something like this:

```zig
mapped_field.value = if (std.mem.eql(u8, field.value, "true")) "en" else "none";
```

Checking for `false` isn't worth it.

2024-08-07 10:45 UTC, KAYT33N commented on src/config/migrator.zig
> +            mapped_field.value = "none";
Thought of it but this returns `none` on everything right ?
Even `en` will return `none` cause its not equal `true`

2024-08-07 12:24 UTC, AnErrupTion commented on src/config/migrator.zig
> +            mapped_field.value = "none";
Ah yes, my bad. In this case, you can just use an `if/else if` statement instead of just two `if`s. Also, `mapped_config_fields` is set incorrectly: it only gets set if at least 1 field needs to be migrated. So, in this case, it needs to be set in either of the two conditions (if `bigclock` is a boolean), else it shouldn't be set.

2024-08-07 13:41 UTC, AnErrupTion approved these changes
LGTM, but please update your branch with the latest changes.

2024-08-07 14:39 UTC, KAYT33N commented
@AnErrupTion 
Rebased with master
Thanks for the help on doing this

2024-08-07 14:47 UTC, AnErrupTion commented
Thanks for your contribution!

2024-08-07 14:47 UTC, merged